name: build
env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.16.1 # Define the elixir version [required]
        otp-version: 25.2 # Define the OTP version [required]

    - name: Get build cache
      uses: actions/cache@v3
      with:
        path: _build/test/
        key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-build-

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix compile

    - name: Check mix format
      run: mix format --check-formatted

    - name: Run Tests
      run: |
        mix coveralls.github
